package demo1;

public class TestException1 {

	public static void main(String[] args) {
		

	}

}

class Calculator{
	public int calcDiv(int n1, int n2){
		try{
			return n1/n2;
		} catch(ArithmeticException e){
			e.printStackTrace();
			
		}
	}
}
